name: Build and Publish Docker Images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  alisten:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for alisten
        id: meta-alisten
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bihua-university/alisten
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push alisten image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alisten.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-alisten.outputs.tags }}
          labels: ${{ steps.meta-alisten.outputs.labels }}

  musiclet:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for musiclet
        id: meta-musiclet
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bihua-university/alisten-musiclet
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push musiclet image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/musiclet.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-musiclet.outputs.tags }}
          labels: ${{ steps.meta-musiclet.outputs.labels }}

